theme: jekyll-theme-midnight
title: Welcome to the "The Dummies guide to Deep Learning"
description: In the process of studying Machine learning and Deep Learning without
a computer science background, I have made several stupid mistakes which I only realised later. 
In this blog I want to share some of the lessons which I have learnt. 
